flagging <- function(mod, c) {
	flag <- 0
	for (a in 1:length(Age.pred)) {
	 if (any(class(mod) == "glm"))
	  pred <- predict(mod, newdata = data.frame(ln.h1 = x.pred, Age = rep(Age.pred[a], m)), type = "response")
	 if (any(class(mod) == "list"))
	  pred <- predict(mod$gam, newdata = data.frame(ln.h1 = x.pred, Age = rep(Age.pred[a], m)), type = "response")
		if (any(class(mod) == "brmsfit"))
	  pred <- fitted(mod, newdata = data.frame(ln.h1 = x.pred, Age = rep(a, m)), type = "response", re_formula = NA)[,1]
	 if (max(pred) > flag) {flag <- max(pred)} 
	}
	cat(paste0("max = ", flag, "\n"))
	return(flag)
}

# f2
c <- 2*max(fruitdata$TotalFruitset)

# bloque 1 
{
mod.f2 <- list()
flags <- c()
mod.f2[[1]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[1]], c))
mod.f2[[2]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[2]], c))
mod.f2[[3]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[3]], c))
mod.f2[[4]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[4]], c))
mod.f2[[5]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[5]], c))
mod.f2[[6]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[6]], c))
mod.f2[[7]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[7]], c))
mod.f2[[8]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[8]], c))
mod.f2[[9]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[9]], c))
mod.f2[[10]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[10]], c))
mod.f2[[11]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[11]], c))
mod.f2[[12]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[12]], c))
mod.f2[[13]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[13]], c))
mod.f2[[14]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(0+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[14]], c))
mod.f2[[15]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4))+(1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[15]], c))
mod.f2[[16]] <- brm(TotalFruitset ~ t2(ln.h1, Age, k = c(4,4)), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[16]], c))
}

# bloque 2
{
mod.f2[[17]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[17]], c))
mod.f2[[18]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[18]], c))
mod.f2[[19]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[19]], c))
mod.f2[[20]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[20]], c))
mod.f2[[21]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[21]], c))
mod.f2[[22]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[22]], c))
mod.f2[[23]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[23]], c))
mod.f2[[24]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[24]], c))
mod.f2[[25]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[25]], c))
mod.f2[[26]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[26]], c))
mod.f2[[27]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[27]], c))
mod.f2[[28]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[28]], c))
mod.f2[[29]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[29]], c))
mod.f2[[30]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[30]], c))
mod.f2[[31]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+s(Age, k = 4), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[31]], c))
}

# bloque 3
{
mod.f2[[32]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+Age+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[32]], c))
mod.f2[[33]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[33]], c))
mod.f2[[34]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[34]], c))
mod.f2[[35]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[35]], c))
mod.f2[[36]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[36]], c))
mod.f2[[37]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[37]], c))
mod.f2[[38]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[38]], c))
mod.f2[[39]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[39]], c))
mod.f2[[40]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[40]], c))
mod.f2[[41]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[41]], c))
mod.f2[[42]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[42]], c))
mod.f2[[43]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[43]], c))
mod.f2[[44]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(0+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[44]], c))
mod.f2[[45]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4)+(1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[45]], c))
mod.f2[[46]] <- brm(TotalFruitset ~ ln.h1+s(Age, k = 4), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[46]], c))
}

# bloque 4
{
mod.f2[[47]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+Age+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[47]], c))
mod.f2[[48]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[48]], c))
mod.f2[[49]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[49]], c))
mod.f2[[50]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[50]], c))
mod.f2[[51]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+ln.h1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[51]], c))
mod.f2[[52]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+Age+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[52]], c))
mod.f2[[53]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+Age+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[53]], c))
mod.f2[[54]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[54]], c))
mod.f2[[55]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[55]], c))
mod.f2[[56]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[56]], c))
mod.f2[[57]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+Age:ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[57]], c))
mod.f2[[58]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+ln.h1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[58]], c))
mod.f2[[59]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(0+Age|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[59]], c))
mod.f2[[60]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age+(1|PlotCode), data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[60]], c))
mod.f2[[61]] <- brm(TotalFruitset ~ s(ln.h1, k = 4)+Age, data = fruitdata, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f2[[61]], c))
}

# f3
c <- 2*max(seeds$N.seed)

# bloque 1
{
mod.f3 <- list()
mod.f3[[1]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[1]], c))
mod.f3[[2]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[2]], c))
mod.f3[[3]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[3]], c))
mod.f3[[4]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[4]], c))
mod.f3[[5]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[5]], c))
mod.f3[[6]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[6]], c))
mod.f3[[7]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[7]], c))
mod.f3[[8]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[8]], c))
mod.f3[[9]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[9]], c))
mod.f3[[10]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[10]], c))
mod.f3[[11]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[11]], c))
mod.f3[[12]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[12]], c))
mod.f3[[13]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[13]], c))
mod.f3[[14]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(0+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[14]], c))
mod.f3[[15]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4))+(1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[15]], c))
mod.f3[[16]] <- brm(N.seed ~ t2(ln.h1, Age, k = c(4,4)), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[16]], c))
}

# bloque 2
{
mod.f3[[17]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[17]], c))
mod.f3[[18]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[18]], c))
mod.f3[[19]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[19]], c))
mod.f3[[20]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[20]], c))
mod.f3[[21]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[21]], c))
mod.f3[[22]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[22]], c))
mod.f3[[23]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[23]], c))
mod.f3[[24]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[24]], c))
mod.f3[[25]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[25]], c))
mod.f3[[26]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[26]], c))
mod.f3[[27]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[27]], c))
mod.f3[[28]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[28]], c))
mod.f3[[29]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(0+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[29]], c))
mod.f3[[30]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4)+(1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[30]], c))
mod.f3[[31]] <- brm(N.seed ~ s(ln.h1, k = 4)+s(Age, k = 4), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[31]], c))
}

# bloque 3
{
mod.f3[[32]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+Age+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[32]], c))
mod.f3[[33]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[33]], c))
mod.f3[[34]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[34]], c))
mod.f3[[35]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[35]], c))
mod.f3[[36]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[36]], c))
mod.f3[[37]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[37]], c))
mod.f3[[38]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[38]], c))
mod.f3[[39]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[39]], c))
mod.f3[[40]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[40]], c))
mod.f3[[41]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[41]], c))
mod.f3[[42]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[42]], c))
mod.f3[[43]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[43]], c))
mod.f3[[44]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(0+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[44]], c))
mod.f3[[45]] <- brm(N.seed ~ ln.h1+s(Age, k = 4)+(1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[45]], c))
mod.f3[[46]] <- brm(N.seed ~ ln.h1+s(Age, k = 4), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[46]], c))
}

# bloque 4
{
mod.f3[[47]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+Age+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[47]], c))
mod.f3[[48]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[48]], c))
mod.f3[[49]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[49]], c))
mod.f3[[50]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[50]], c))
mod.f3[[51]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+ln.h1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[51]], c))
mod.f3[[52]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+Age+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[52]], c))
mod.f3[[53]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+Age+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[53]], c))
mod.f3[[54]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[54]], c))
mod.f3[[55]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[55]], c))
mod.f3[[56]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[56]], c))
mod.f3[[57]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+Age:ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[57]], c))
mod.f3[[58]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+ln.h1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[58]], c))
mod.f3[[59]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(0+Age|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[59]], c))
mod.f3[[60]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age+(1|Plot), data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[60]], c))
mod.f3[[61]] <- brm(N.seed ~ s(ln.h1, k = 4)+Age, data = seeds, family = negbinomial, cores = 4, iter = 2000, control = list(adapt_delta = 0.9999))
flags <- c(flags, flagging(mod.f3[[61]], c))
}

# f4
glm.f2.betareg <- betareg(Establishment ~ Age, data = tot_seeds_t1)




